version: "3.7"

services:
    # Database
    db:
        platform: linux/x86_64
        image: mysql:5.7
        container_name: $DB_CONTAINER_NAME
        volumes:
            - database:/var/lib/mysql
        restart: always
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: $MYSQL_DATABASE
            MYSQL_USER: $MYSQL_USER
            MYSQL_PASSWORD: $MYSQL_ROOT_PASSWORD
        ports:
            - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
volumes:
    database:
